"""Redis Lua scripts compiled by redis-lua-py from redis_scripts.event_streams. Do not edit.

Each script is a function taking a redis-py client, sync or async, and then the
arguments it was written with. Its Lua is the constant of the same name in
capitals.

Regenerate with:

    python -m redis_lua_py generate redis_scripts.event_streams --out agno/os/event_streams/_redis_lua.py
"""

from __future__ import annotations

from collections.abc import Awaitable, Iterable
from typing import Any, Protocol, Union, overload
from weakref import WeakKeyDictionary

__all__ = [
    "FENCED_INCR",
    "FENCED_XADD",
    "fenced_incr",
    "fenced_xadd",
]


#: What a generated signature accepts for a key, the same as redis-py does.
_Key = Union[str, bytes, memoryview]

#: What a generated signature accepts for an argument it has no better type for.
_Arg = Union[str, bytes, memoryview, int, float]


class _SyncClient(Protocol):
    """Enough of a sync redis-py client to type its call before the async one.

    ``__enter__`` is the discriminator because every sync redis-py client has
    one and no async client does. Checked first, it keeps a wrapper that
    forwards everything through ``__getattr__`` -- which mypy takes to supply
    ``__aenter__`` as well -- from being typed as async.
    """

    def __enter__(self) -> Any: ...

    def register_script(self, script: str) -> Any: ...


class _AsyncClient(Protocol):
    """Enough of an async redis-py client to tell it from a sync one.

    Only used to type the two shapes of call. ``__aenter__`` is the
    discriminator because every async client has one and no sync client does,
    on every supported redis-py -- ``aclose`` only arrived in redis-py 5.
    """

    async def __aenter__(self) -> Any: ...

    def register_script(self, script: str) -> Any: ...


def _encode(
    name: str, value: object, error: type[Exception] = TypeError
) -> str | bytes | memoryview:
    """Render a Python value as a Redis argument.

    Redis has no argument types: everything on the wire is a byte string. This
    only accepts values whose string form is unambiguous, so that a stray None
    or object fails here rather than arriving in Lua as something surprising.
    """
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (str, bytes, memoryview)):
        return value
    if isinstance(value, (int, float)):
        return repr(value) if isinstance(value, float) else str(value)
    raise error(
        f"argument {name!r} is a {type(value).__name__}, which has no Redis representation. "
        "Pass a str, bytes, int, float or bool."
    )


def _items(name: str, value: object, error: type[Exception] = TypeError) -> list[Any]:
    """The elements passed for a list parameter.

    A string is iterable too, and splitting a key into characters is never
    what was meant, so it is refused rather than spread.
    """
    if isinstance(value, (str, bytes, memoryview)) or not isinstance(value, Iterable):
        raise error(
            f"argument {name!r} takes a list, got a {type(value).__name__}. "
            "Wrap a single value in a list."
        )
    return list(value)


def _encode_all(
    name: str, value: object, error: type[Exception] = TypeError
) -> list[str | bytes | memoryview]:
    """The elements passed for a list of arguments, each rendered for Redis."""
    return [_encode(name, item, error) for item in _items(name, value, error)]


def _is_cluster_pipeline(client: object) -> bool:
    cls = type(client)
    return cls.__name__ == "ClusterPipeline" and cls.__module__.startswith("redis.")


def _registered(lua: str, registry: WeakKeyDictionary[Any, Any], client: Any) -> Any:
    """The redis-py Script for this source on this client, registered once.

    redis-py's own Script object already implements the EVALSHA-then-EVAL
    dance and the NOSCRIPT retry, so this defers to it rather than
    reimplementing script caching.
    """
    try:
        registered = registry.get(client)
    except TypeError:  # a client that does not support weak references
        return client.register_script(lua)
    if registered is None:
        registered = client.register_script(lua)
        registry[client] = registered
    return registered


def _run(
    lua: str,
    registry: WeakKeyDictionary[Any, Any],
    client: Any,
    keys: list[Any],
    argv: list[Any],
) -> Any:
    """Run a script: a value from a sync client, an awaitable from an async one."""
    if _is_cluster_pipeline(client):
        # redis-py refuses EVALSHA on a cluster pipeline, and a queued
        # EVALSHA could not recover from NOSCRIPT at execute time anyway,
        # so the source travels with the command.
        return client.eval(lua, len(keys), *keys, *argv)
    return _registered(lua, registry, client)(keys=keys, args=argv, client=client)


# fenced_incr -- KEYS: gen_key, counter_key; ARGV: generation, ttl
FENCED_INCR = """\
-- fenced_incr
-- Generated by redis-lua-py from redis_scripts/event_streams.py:20. Do not edit.
-- A Redis command with nothing to return hands Lua false, not nil, so an
-- `is None` test has to accept both. Taking v as an argument also means the
-- operand is evaluated once, not once per comparison.
local function __isnil(v)
  return v == nil or v == false
end
-- Python's int(): a number truncated toward zero, and an error rather than
-- nil for anything that is not a number.
local function __int(v)
  local n = tonumber(v)
  if n == nil then error('invalid literal for int(): ' .. tostring(v), 0) end
  if n < 0 then return math.ceil(n) end
  return math.floor(n)
end
local gen_key = KEYS[1]
local counter_key = KEYS[2]
local generation = tonumber(ARGV[1])
local ttl = ARGV[2]
local gen = redis.call('GET', gen_key)
if __isnil(gen) then
  redis.call('SET', gen_key, generation, 'EX', ttl)
elseif __int(gen) > generation then
  return -1
elseif __int(gen) < generation then
  redis.call('SET', gen_key, generation, 'EX', ttl)
end
return redis.call('INCR', counter_key)
"""
_FENCED_INCR_CLIENTS: WeakKeyDictionary[Any, Any] = WeakKeyDictionary()


@overload
def fenced_incr(
    client: _SyncClient,
    /,
    gen_key: _Key,
    counter_key: _Key,
    generation: int,
    ttl: int,
) -> int: ...
@overload
def fenced_incr(
    client: _AsyncClient,
    /,
    gen_key: _Key,
    counter_key: _Key,
    generation: int,
    ttl: int,
) -> Awaitable[int]: ...
@overload
def fenced_incr(
    client: Any,
    /,
    gen_key: _Key,
    counter_key: _Key,
    generation: int,
    ttl: int,
) -> int: ...
def fenced_incr(
    client: Any,
    /,
    gen_key: _Key,
    counter_key: _Key,
    generation: int,
    ttl: int,
) -> Any:
    """Return the incremented counter, or -1 when a newer generation owns the stream."""
    return _run(
        FENCED_INCR,
        _FENCED_INCR_CLIENTS,
        client,
        [gen_key, counter_key],
        [_encode("generation", generation), _encode("ttl", ttl)],
    )


# fenced_xadd -- KEYS: gen_key, stream_key; ARGV: generation, maxlen, idx, sse
FENCED_XADD = """\
-- fenced_xadd
-- Generated by redis-lua-py from redis_scripts/event_streams.py:33. Do not edit.
-- A Redis command with nothing to return hands Lua false, not nil, so an
-- `is None` test has to accept both. Taking v as an argument also means the
-- operand is evaluated once, not once per comparison.
local function __isnil(v)
  return v == nil or v == false
end
-- Python's int(): a number truncated toward zero, and an error rather than
-- nil for anything that is not a number.
local function __int(v)
  local n = tonumber(v)
  if n == nil then error('invalid literal for int(): ' .. tostring(v), 0) end
  if n < 0 then return math.ceil(n) end
  return math.floor(n)
end
local gen_key = KEYS[1]
local stream_key = KEYS[2]
local generation = tonumber(ARGV[1])
local maxlen = ARGV[2]
local idx = ARGV[3]
local sse = ARGV[4]
local gen = redis.call('GET', gen_key)
if not __isnil(gen) and __int(gen) > generation then
  return 0
end
redis.call('XADD', stream_key, 'MAXLEN', '~', maxlen, '*', 'idx', idx, 'sse', sse)
return 1
"""
_FENCED_XADD_CLIENTS: WeakKeyDictionary[Any, Any] = WeakKeyDictionary()


@overload
def fenced_xadd(
    client: _SyncClient,
    /,
    gen_key: _Key,
    stream_key: _Key,
    generation: int,
    maxlen: int,
    idx: int,
    sse: str,
) -> int: ...
@overload
def fenced_xadd(
    client: _AsyncClient,
    /,
    gen_key: _Key,
    stream_key: _Key,
    generation: int,
    maxlen: int,
    idx: int,
    sse: str,
) -> Awaitable[int]: ...
@overload
def fenced_xadd(
    client: Any,
    /,
    gen_key: _Key,
    stream_key: _Key,
    generation: int,
    maxlen: int,
    idx: int,
    sse: str,
) -> int: ...
def fenced_xadd(
    client: Any,
    /,
    gen_key: _Key,
    stream_key: _Key,
    generation: int,
    maxlen: int,
    idx: int,
    sse: str,
) -> Any:
    """Append the event and return 1, or 0 when a newer generation owns the stream."""
    return _run(
        FENCED_XADD,
        _FENCED_XADD_CLIENTS,
        client,
        [gen_key, stream_key],
        [
            _encode("generation", generation),
            _encode("maxlen", maxlen),
            _encode("idx", idx),
            _encode("sse", sse),
        ],
    )
