blank_issues_enabled: false
contact_links:
  - name: Ask a question or discuss
    url: https://github.com/microsoft/agno/discussions # Adjust if the repo has a different discussion forum/channel
    about: Please ask and answer questions here.
