"""
Custom Follow-up Instructions via FollowupConfig
==================================================

Demonstrates how to use the `followup_config` parameter (a `FollowupConfig`
object) to customize how follow-up suggestions are generated by the agent.

`FollowupConfig` houses all follow-up generation settings in one place:
- `model`        — which model generates the follow-ups (optional)
- `instructions` — custom instructions to shape tone, style, or domain focus

The existing `followup_model` parameter is still supported for backward
compatibility.
"""

from agno.agent import Agent
from agno.agent.followup import FollowupConfig
from agno.models.openai import OpenAIChat

# ---------------------------------------------------------------------------
# Agent without custom follow-up config (default behavior)
# ---------------------------------------------------------------------------
default_agent = Agent(
    model=OpenAIChat(id="gpt-4o-mini"),
    followups=True,
    num_followups=3,
    markdown=True,
)

# ---------------------------------------------------------------------------
# Agent with FollowupConfig providing custom instructions
# ---------------------------------------------------------------------------
custom_agent = Agent(
    model=OpenAIChat(id="gpt-4o-mini"),
    followups=True,
    num_followups=3,
    followup_config=FollowupConfig(
        instructions=(
            "Always phrase follow-up suggestions as formal questions ending with a question mark. "
            "Focus only on practical, actionable next steps the user can take immediately."
        ),
    ),
    markdown=True,
)

# ---------------------------------------------------------------------------
# Agent where followup_config also overrides the model used for follow-ups
# ---------------------------------------------------------------------------
model_override_agent = Agent(
    model=OpenAIChat(id="gpt-4o-mini"),
    followups=True,
    num_followups=3,
    followup_config=FollowupConfig(
        model=OpenAIChat(id="gpt-4o-mini"),
        instructions="Keep follow-ups concise — no more than 6 words each.",
    ),
    markdown=True,
)

PROMPT = "Explain the key differences between REST and GraphQL APIs."

if __name__ == "__main__":
    print("=== Default follow-ups (no custom config) ===")
    response = default_agent.run(PROMPT)
    print("Follow-ups:", response.followups)

    print()
    print("=== Custom follow-ups via FollowupConfig.instructions ===")
    response = custom_agent.run(PROMPT)
    print("Follow-ups:", response.followups)

    print()
    print("=== Custom follow-ups with model override via FollowupConfig ===")
    response = model_override_agent.run(PROMPT)
    print("Follow-ups:", response.followups)
