"""Grouped settings dataclasses for Agent, Team and Workflow constructor parameters.

Settings objects are input-only: the constructor unpacks them onto the flat
attributes, so `agent.session_id` etc. keep working unchanged. None means
"not set" and falls back to the flat parameter (so a settings field cannot
explicitly set a parameter to None); non-None flat defaults are recorded in
the field metadata under "flat_default". If a parameter is set both ways,
the settings object wins and a warning is logged if the values differ.

Example:
    from agno.agent import Agent
    from agno.settings import SessionSettings

    agent = Agent(session_settings=SessionSettings(session_id="my-session"))
    agent.session_id  # "my-session"
"""

from __future__ import annotations

from dataclasses import MISSING, dataclass, field, fields
from typing import (
    TYPE_CHECKING,
    Any,
    Callable,
    Dict,
    List,
    Literal,
    Optional,
    Type,
    Union,
)

from agno.utils.log import log_warning

if TYPE_CHECKING:
    from pydantic import BaseModel

    from agno.agent.agent import Agent
    from agno.compression.manager import CompressionManager
    from agno.culture.manager import CultureManager
    from agno.filters import FilterExpr
    from agno.knowledge.protocol import KnowledgeProtocol
    from agno.learn.machine import LearningMachine
    from agno.memory import MemoryManager
    from agno.models.base import Model
    from agno.models.fallback import FallbackConfig
    from agno.models.message import Message
    from agno.run.agent import RunEvent
    from agno.run.team import TeamRunEvent
    from agno.run.workflow import WorkflowRunEvent
    from agno.session import SessionSummaryManager
    from agno.team.mode import TeamMode


@dataclass
class ModelSettings:
    """Model selection and fallback behavior."""

    # Model to use
    model: Optional[Union[Model, str]] = None
    # Fallback models tried when the primary model fails
    fallback_models: Optional[List[Union[Model, str]]] = None
    # Fallback configuration for model failures (advanced: error-specific routing)
    fallback_config: Optional[FallbackConfig] = None


@dataclass
class SessionSettings:
    """Session identity, state and past-session search."""

    # Default session_id (autogenerated if not set)
    session_id: Optional[str] = None
    # Default session state (stored in the database to persist across runs)
    session_state: Optional[Dict[str, Any]] = None
    # Set to True to add the session_state to the context
    add_session_state_to_context: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Set to True to give the model tools to update the session_state dynamically
    enable_agentic_state: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Set to True to overwrite the stored session_state with the session_state provided in the run. Default behaviour merges the current session state with the session state in the db
    overwrite_db_session_state: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, cache the current session in memory for faster access
    cache_session: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add a tool to search past sessions
    search_past_sessions: Optional[bool] = field(default=None, metadata={"flat_default": False})
    num_past_sessions_to_search: Optional[int] = None
    num_past_session_runs_in_search: Optional[int] = None
    # If True, create/update session summaries at the end of runs
    enable_session_summaries: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add session summaries to the context
    add_session_summary_to_context: Optional[bool] = None
    # Session summary manager
    session_summary_manager: Optional[SessionSummaryManager] = None


@dataclass
class ContextSettings:
    """Context building: datetime/location, formatting and message roles."""

    # If markdown=True, add instructions to format the output using markdown
    markdown: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add the name to the instructions
    add_name_to_context: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add the current datetime to the instructions
    add_datetime_to_context: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add the current location to the instructions
    add_location_to_context: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Custom datetime format string (e.g. "%Y-%m-%d %H:%M:%S")
    datetime_format: Optional[str] = None
    # Custom timezone for datetime instructions following the TZ Database format (e.g. "Etc/UTC")
    timezone_identifier: Optional[str] = None
    # If True, resolve session_state, dependencies, and metadata in the user and system messages
    resolve_in_context: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # Additional context added to the end of the system message
    additional_context: Optional[str] = None
    # A list of extra messages added after the system message and before the user message
    additional_input: Optional[List[Union[str, Dict, BaseModel, Message]]] = None
    # Dependencies available for tools and prompt functions
    dependencies: Optional[Dict[str, Any]] = None
    # If True, add the dependencies to the user prompt
    add_dependencies_to_context: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, wrap instructions in <instructions> tags
    use_instruction_tags: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Role for the system message
    system_message_role: Optional[str] = field(default=None, metadata={"flat_default": "system"})
    # Role for the user message (Agent only)
    user_message_role: Optional[str] = field(default=None, metadata={"flat_default": "user"})
    # Set to False to skip context building (Agent only)
    build_context: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # Set to False to skip building the user context (Agent only)
    build_user_context: Optional[bool] = field(default=None, metadata={"flat_default": True})


@dataclass
class KnowledgeSettings:
    """Knowledge base access, retrieval and knowledge tools."""

    knowledge: Optional[Union[KnowledgeProtocol, Callable[..., KnowledgeProtocol]]] = None
    # Filters to apply when searching the knowledge base
    knowledge_filters: Optional[Union[Dict[str, Any], List[FilterExpr]]] = None
    # Let the model choose the knowledge filters
    enable_agentic_knowledge_filters: Optional[bool] = None
    # Enable RAG by adding references from Knowledge to the user prompt
    add_knowledge_to_context: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Retrieval function to get references, used instead of the default search_knowledge function
    knowledge_retriever: Optional[Callable[..., Optional[List[Union[Dict, str]]]]] = None
    references_format: Optional[Literal["json", "yaml"]] = field(default=None, metadata={"flat_default": "json"})
    # Add a tool that allows the Model to search the knowledge base (aka Agentic RAG)
    # Added only if knowledge is provided.
    search_knowledge: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # If True, add search_knowledge instructions to the system prompt
    add_search_knowledge_instructions: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # Add a tool that allows the Model to update Knowledge
    update_knowledge: Optional[bool] = field(default=None, metadata={"flat_default": False})


@dataclass
class MemorySettings:
    """User memory creation and recall."""

    # Memory manager to use
    memory_manager: Optional[MemoryManager] = None
    # Enable the model to manage memories of the user
    enable_agentic_memory: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, create/update user memories at the end of runs
    update_memory_on_run: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add a reference to the user memories in the context
    add_memories_to_context: Optional[bool] = None


@dataclass
class HistorySettings:
    """Chat history sent to the model and history tools."""

    # Add messages from the chat history to the messages list sent to the Model
    add_history_to_context: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Number of historical runs to include in the messages
    num_history_runs: Optional[int] = None
    # Number of historical messages to include in the messages list sent to the Model
    num_history_messages: Optional[int] = None
    # Maximum number of tool calls to include from history (None = no limit)
    max_tool_calls_from_history: Optional[int] = None
    # Add a tool that allows the Model to read the chat history
    read_chat_history: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Add a tool that allows the Model to get the tool call history (Agent only)
    read_tool_call_history: Optional[bool] = field(default=None, metadata={"flat_default": False})


@dataclass
class OutputSettings:
    """Input/output schemas, parsing and response models."""

    # Provide an input schema to validate the input
    input_schema: Optional[Type[BaseModel]] = None
    # Provide a response model to get the response in the implied format.
    # You can use a Pydantic model or a JSON fitting the provider's expected schema.
    output_schema: Optional[Union[Type[BaseModel], Dict[str, Any]]] = None
    # Provide a secondary model to parse the response from the primary model
    parser_model: Optional[Union[Model, str]] = None
    # Provide a prompt for the parser model
    parser_model_prompt: Optional[str] = None
    # Provide an output model to structure the response from the main model
    output_model: Optional[Union[Model, str]] = None
    # Provide a prompt for the output model
    output_model_prompt: Optional[str] = None
    # If True, the response from the Model is converted into the output_schema
    # Otherwise, the response is returned as a JSON string
    parse_response: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # Use model enforced structured_outputs if supported (Agent only)
    structured_outputs: Optional[bool] = None
    # Add a JSON description of the output schema to the system message instead of using the provider schema
    use_json_mode: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Save the response to a file (Agent only)
    save_response_to_file: Optional[str] = None


@dataclass
class ToolSettings:
    """Tool call limits, choice and hooks."""

    # Maximum number of tool calls allowed
    tool_call_limit: Optional[int] = None
    # Controls which (if any) tool is called by the model
    tool_choice: Optional[Union[str, Dict[str, Any]]] = None
    # A function that acts as middleware and is called around tool calls
    tool_hooks: Optional[List[Callable]] = None
    # If False, media (images, videos, audio, files) is only available to tools and not sent to the LLM
    send_media_to_model: Optional[bool] = field(default=None, metadata={"flat_default": True})


@dataclass
class ReasoningSettings:
    """Step-by-step reasoning before answering."""

    # Enable reasoning by working through the problem step by step
    reasoning: Optional[bool] = field(default=None, metadata={"flat_default": False})
    reasoning_model: Optional[Union[Model, str]] = None
    reasoning_agent: Optional[Agent] = None
    reasoning_min_steps: Optional[int] = field(default=None, metadata={"flat_default": 1})
    reasoning_max_steps: Optional[int] = field(default=None, metadata={"flat_default": 10})


@dataclass
class StorageSettings:
    """What gets stored in the run output."""

    # If True, store media in run output
    store_media: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # If True, store tool results in run output
    store_tool_messages: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # If True, store history messages in run output
    store_history_messages: Optional[bool] = field(default=None, metadata={"flat_default": False})


@dataclass
class EventSettings:
    """Streaming and event persistence."""

    # Stream the response
    stream: Optional[bool] = None
    # Stream the intermediate steps
    stream_events: Optional[bool] = None
    # Stream events from executors (agents/teams/functions) within steps (Workflow only)
    stream_executor_events: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # Persist the events on the run response
    store_events: Optional[bool] = field(default=None, metadata={"flat_default": False})
    events_to_skip: Optional[List[Union[RunEvent, TeamRunEvent, WorkflowRunEvent]]] = None


@dataclass
class FollowupSettings:
    """Followup prompt generation after the main response."""

    # If True, generate followup prompts after the main response
    followups: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Number of followup prompts to generate
    num_followups: Optional[int] = field(default=None, metadata={"flat_default": 3})
    # Optional model to use for generating followups
    followup_model: Optional[Union[Model, str]] = None


@dataclass
class RetrySettings:
    """Retry behavior for failed runs."""

    # Number of retries to attempt
    retries: Optional[int] = field(default=None, metadata={"flat_default": 0})
    # Delay between retries (in seconds)
    delay_between_retries: Optional[int] = field(default=None, metadata={"flat_default": 1})
    # Exponential backoff: if True, the delay between retries is doubled each time
    exponential_backoff: Optional[bool] = field(default=None, metadata={"flat_default": False})


@dataclass
class DebugSettings:
    """Debug logs and telemetry."""

    # Enable debug logs
    debug_mode: Optional[bool] = field(default=None, metadata={"flat_default": False})
    debug_level: Optional[Literal[1, 2]] = field(default=None, metadata={"flat_default": 1})
    # Log minimal telemetry for analytics
    telemetry: Optional[bool] = field(default=None, metadata={"flat_default": True})


@dataclass
class CompressionSettings:
    """Tool result compression to save context."""

    # If True, compress tool call results to save context
    compress_tool_results: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Compression manager for compressing tool call results
    compression_manager: Optional[CompressionManager] = None


@dataclass
class CacheSettings:
    """Caching of callable factory results."""

    # Enable caching of callable factory results
    cache_callables: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # Custom cache key function for tools callable factory
    callable_tools_cache_key: Optional[Callable[..., Optional[str]]] = None
    # Custom cache key function for knowledge callable factory
    callable_knowledge_cache_key: Optional[Callable[..., Optional[str]]] = None
    # Custom cache key function for members callable factory (Team only)
    callable_members_cache_key: Optional[Callable[..., Optional[str]]] = None


@dataclass
class LearningSettings:
    """Unified learning capabilities."""

    # LearningMachine for unified learning capabilities
    learning: Optional[Union[bool, LearningMachine]] = None
    # Add learnings context to system prompt
    add_learnings_to_context: Optional[bool] = field(default=None, metadata={"flat_default": True})


@dataclass
class CultureSettings:
    """Cultural knowledge management (Agent only, experimental)."""

    # Culture manager to use
    culture_manager: Optional[CultureManager] = None
    # Enable the agent to manage cultural knowledge
    enable_agentic_culture: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Update cultural knowledge after every run
    update_cultural_knowledge: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add cultural knowledge to the context
    add_culture_to_context: Optional[bool] = None


@dataclass
class DelegationSettings:
    """Team member coordination and delegation (Team only)."""

    # Team execution mode. When set, overrides the boolean flags below.
    mode: Optional[TeamMode] = None
    # If True, the team leader won't process responses from the members and instead will return them directly
    # Should not be used in combination with delegate_to_all_members
    respond_directly: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Set to false if you want to send the run input directly to the member agents
    determine_input_for_members: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # If True, the team leader will delegate the task to all members, instead of deciding for a subset
    delegate_to_all_members: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Maximum number of iterations for autonomous task loop (mode=tasks)
    max_iterations: Optional[int] = field(default=None, metadata={"flat_default": 10})
    # If True, send team-level history to members
    add_team_history_to_members: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # Number of historical team runs to include for members
    num_team_history_runs: Optional[int] = field(default=None, metadata={"flat_default": 3})
    # If True, share all member request/response interactions with delegated members
    share_member_interactions: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add member tools to the team context
    add_member_tools_to_context: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, add a tool to get member information
    get_member_information_tool: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, store member agent runs inside the team's RunOutput
    store_member_responses: Optional[bool] = field(default=None, metadata={"flat_default": False})
    # If True, stream member events from the Team
    stream_member_events: Optional[bool] = field(default=None, metadata={"flat_default": True})
    # Enable member logs - Sets the debug_mode for team and members
    show_members_responses: Optional[bool] = field(default=None, metadata={"flat_default": False})


def _flat_default(settings: Any, name: str) -> Any:
    for f in fields(settings):
        if f.name == name:
            return f.metadata.get("flat_default")
    raise AttributeError(f"{type(settings).__name__} has no field {name!r}")


def _values_differ(value: Any, other: Any) -> bool:
    try:
        return bool(value != other)
    except Exception:
        return value is not other


def resolve_setting(settings: Optional[Any], name: str, flat_value: Any, flat_default: Any = MISSING) -> Any:
    """Resolve a flat constructor parameter against a grouped settings object.

    Returns the settings value when the settings object sets the field (i.e. it
    is not None), otherwise the flat value. If both are set to different values,
    the settings object wins with a warning.
    """
    if settings is None:
        return flat_value
    settings_value = getattr(settings, name)
    if settings_value is None:
        return flat_value
    if flat_default is MISSING:
        flat_default = _flat_default(settings, name)
    if _values_differ(flat_value, settings_value) and _values_differ(flat_value, flat_default):
        log_warning(
            f"Both `{name}` and `{type(settings).__name__}.{name}` provided. Using the value from `{type(settings).__name__}`."
        )
    return settings_value


def warn_unsupported_setting(settings: Optional[Any], name: str, owner: str) -> None:
    """Warn when a settings field is set but not supported by the receiving class."""
    if settings is not None and getattr(settings, name) is not None:
        log_warning(f"`{type(settings).__name__}.{name}` is not supported by {owner} and will be ignored.")
