"""
Get an API key at https://gandr.ai

The toolkit uses `httpx`, which installs with agno. No extra dependencies are needed.
"""

from agno.agent import Agent
from agno.tools.gandr import GandrTools
from agno.utils.audio import write_audio_to_file

# ---------------------------------------------------------------------------
# Create Agent
# ---------------------------------------------------------------------------


# Initialize Agent with Gandr tools
agent = Agent(
    name="Gandr TTS Agent",
    description="An agent that uses Gandr for text-to-speech.",
    tools=[GandrTools()],
)

# ---------------------------------------------------------------------------
# Run Agent
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    response = agent.run(
        """Generate a simple greeting using Text-to-Speech:

        Say "Welcome to Gandr. This speech is generated by an agent."
        """
    )

    # Save the generated audio
    if response.audio:
        write_audio_to_file(
            audio=response.audio[0].content, filename="tmp/greeting.mp3"
        )
