name: PR Lint

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  lint-pr:
    name: Lint PR Title and Body
    runs-on: ubuntu-latest
    steps:
      - name: Check PR Title Format
        run: |
          TITLE="${{ github.event.pull_request.title }}"
          REGEX="^\[(feat|fix|docs|test|refactor|build|ci|chore|perf|style|revert)\]\\s*.+"
          if [[ ! "$TITLE" =~ $REGEX ]]; then
            echo "❌ PR Title '$TITLE' does not match the required format '[type] subject'."
            echo "   Please start your PR title with a valid type like [feat], [fix], [docs], etc., followed by a space and the subject."
            exit 1
          else
            echo "✅ PR Title format is valid."
          fi

      - name: Check Linked Issue
        run: |
          BODY="${{ github.event.pull_request.body }}"
          REGEX="(closes|fixes|resolves) #[0-9]+"
          if [[ ! "$BODY" =~ $REGEX ]]; then
            echo "❌ PR description does not link to an issue using 'fixes #<issue_number>', 'closes #<issue_number>', or 'resolves #<issue_number>'."
            echo "   Please add the required keyword and issue number to the PR description."
            exit 1
          else
            echo "✅ PR description links to an issue."
          fi
